# Generated by Django 3.2 on 2021-05-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OxygenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('businessName', models.CharField(max_length=100)),
                ('personName', models.CharField(max_length=20)),
                ('contact', models.IntegerField(max_length=10)),
                ('verifiedStatus', models.CharField(max_length=10)),
                ('timeStamp', models.TimeField()),
            ],
            options={
                'ordering': ['verifiedStatus', 'timeStamp'],
            },
        ),
    ]
