# Generated by Django 3.2 on 2021-05-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OxyAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oxygenmodel',
            name='timeStamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='oxygenmodel',
            name='verifiedStatus',
            field=models.BooleanField(),
        ),
    ]
